### PR TITLE
Qml essentials 16

### LINKED ISSUE #25: [FR] Outsource logic
For modularisation and reuse of the logic in a different context it would be nice if the python files computing expressibility and entangling capability are outsourced and versioned in another repository.

### PR DESCRIPTION
**Pull request by stroblme**
This PR adds the latest qml essentials package and resolves #25 

- [x] switch to entanglement calculation from qml essentials
- [x] switch to expressibility calculation from qml essentials

### CODE REVIEW

**Comment by stroblme** [comment]
not sure why flake refuses to ignore E203.. anyway, E501 should be treated in the corresponding issue #38

**Review by majafranz — APPROVED** [review]
Lgtm. Great work, Thanks!

**Comment by stroblme** [comment]
expressibility is not quite working yet..

**Comment by majafranz** [comment]
We also need an update to qml-essentials 0.1.16, once released

**Comment by stroblme** [comment]
awesome, thanks!
I'm sometimes getting an error when calculating entanglement, but I'll move that to #39

**Pull request merged**
